In [7]:
# 리스트 + 리스트의 결과

a = [1,2,3]
b = [10, 20, 30]

In [8]:
2* a+b

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [9]:
import numpy as np

In [12]:
# 넘파이로 벡터화 연산을 만든다.

# 벡터 연산은 비교와 논리연산 모두가 가능하다.

an = np.array(a)
bn = np.array(b)

In [13]:
2* an + b

array([12, 24, 36])

In [14]:
an

array([1, 2, 3])

In [15]:
an ==2

array([False,  True, False])

In [16]:
an == np.array([2,2,2])

array([False,  True, False])

In [17]:
bn

array([10, 20, 30])

In [19]:
bn < 20

array([ True, False, False])

In [20]:
True == 1

True

In [21]:
False == 0

True

In [23]:
(an == 2 ) & (bn > 10)

array([False,  True, False])

In [25]:
# 2차원 배열을 수학에서 행렬(matrix)라고 칭한다.

# 다음과 같이 리스트를 중첩해서 2차원 배열처럼 생성할 수 있다.
# 안쪽 리스트의 길이는 열(row)가 되고, 바깥쪽 리스트의 길이는 행(column)이 된다. 

c = np.array([[0, 1, 2],[3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
len(c)

2

In [27]:
len(c[0])

3

In [28]:
c.shape

(2, 3)

In [30]:
x = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [36]:
# 2x3x4
d = np.array ([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
             [[11,12,12,14],
              [15,16,17,18],
              [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 12, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [34]:
# 깊이, 행, 열 구하는 방법

len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [39]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [41]:
# ndim이라는 속성은 차원이 몇 차원인지를 알려준다.
c = np.array([[0,1,2],[3,4,5]])

print(c.ndim)
print(c.shape)

2
(2, 3)


In [42]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [43]:
# 일차원 배열의 인덱싱은 리스트의 인덱싱과 같다.
a = np.array([0, 1,2,3,4])
a[2]
a[-1]

4

In [44]:
# 다차원 배열의 인덱싱은 콤마를 사용해 접근한다.
# 콤마로 구분된 차원을 축이라고도 한다. 그래프의 x축과 y축과도 같다.
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
a[0,0]

0

In [46]:
a[0,1]

1

In [47]:
a[-1,-1]

5

In [80]:
a[0, 1:]

array([1, 2, 3])

In [81]:
a = [[0,1,2,3],[4,5,6,7]]
a

[[0, 1, 2, 3], [4, 5, 6, 7]]

In [85]:
a[0]

[0, 1, 2, 3]

In [92]:
a[0][1:4]

[1, 2, 3]

In [93]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
a[0, :]

array([0, 1, 2, 3])

In [101]:
a[0 :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [102]:
a[:, 1]

array([1, 5])

In [104]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [103]:
a[1,1:]

array([5, 6, 7])

In [105]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]
             ])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [107]:
m[1,2]

7

In [108]:
m[2,4]

14

In [111]:
m[1,1:3]

array([6, 7])

In [138]:
m[1:3, 2:3]

array([[ 7],
       [12]])

In [147]:
m[1:, 2]

array([ 7, 12])

In [148]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

#### 크기가 정해져 있고 모든 값이 0인 배열을 생성할 때는 zeros메서드를 사용
#### 첫번째 인수로는 shape 혹은 1차원 배열 크기를 뜻하는 정수를 넣는다.

###### np.zeros(), ones
###### zeros_like, ones_like
###### empty
###### arange
###### linspace, logspace

#### 배열 생성
###### shape를 의미하는 튜플 값을 첫 번째 인수로 입력하면 다차원 배열도 쉽게 만들 수 있습니다.
###### array 명령과 마찬가지로 dtype 인수를 명시하면 해당 자료형 요소를 가진 배열을 만듭니다. 

In [153]:
# dtype라는 인수로 자료형을 명시해 줄 수도 있다.
# 기본적으로는 float(실수)인데 int로 명시

c = np.zeros((5, 2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [154]:
c.dtype

dtype('int32')

In [155]:
c.shape

(5, 2)

In [162]:
# 빈 스트링 생성

d = np.zeros(5, dtype = "U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [163]:
# 순서대로 데이터가 들어간다.
# 빈 부분은 빈 그대로 남음.

d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" # 4개까지밖에 못들어가서 E는 잘리게 된다. (U4 == 글자 4개까지만 허용)
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [165]:
# 0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용한다.
# 정수

e = np.ones((2, 3, 4), dtype="i")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [166]:
np.ones((2,3,4)).dtype

dtype('float64')

In [172]:
# 스트링으로 변환
e = np.ones((2, 3, 4), dtype="U5")
e

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U5')

In [173]:
f = np.ones

In [174]:
test = np.array([10, 20, 22])

In [175]:
np.ones_like(test, dtype='f')

array([1., 1., 1.], dtype=float32)

In [176]:
# 배열의 크기가 커지면 배열을 초기화 하는데도 시간이 걸린다.
# 이 시간을 단축하기 위해 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용할 수 있다.
# empty 명령으로 생성된 배열에는 기존에 메모리에 저장되었던 값이 있는 것이여서
# 배열의 요소의 값을 미리 알 수 없다.

g = np.empty((4,3))
g

array([[2.12199579e-314, 2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314, 2.12199579e-314]])

In [178]:
# arange 명령은 numpy의 range 명령이라고 볼 수 있다. 
# 특정한 규칙에 따라 증가하는 수열을 만든다.

np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
# 시작, 끝(포함x), 단계

np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [185]:
# 배열 생성
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
# 5개 숫자를 같은 차이, 범위값으로 생성한다.

ex = np.linspace(0, 100, 5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [188]:
ex = np.linspace(1, 100, 100)
ex

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [189]:
# 로그 간격으로 동일하게 만들어준다.

ex2 = np.logspace(0, 100, 5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [192]:
# 전치 연산
# 전치 연산은 행과 열을 바꾸는 작업이다.
# 배열의 T 속성으로 구할 수 있다. 
# *** 메서드가 아닌 속성임에 유의한다. ***

A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [197]:
# range 같은 거여서 0부터 11까지 1씩 증가하는 걸 만듦

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
# a의 모양, 쉐입을 바꾸고 싶을때 사용.
# 3칸짜리 행과 4칸짜리 열을 가지는 3x4 배열을 만들자

b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
# 사용하는 원소의 개수가 정해져 있기 때문에
# reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다.
# -1을 넣으면 해당 숫자는 다른 값에서 계산되어 사용된다. 

# 뒤가 어떤 크기인지는 모르겠지만 일단 3행으로 만들어라.
# -1은 너가 알아서 나누어 떨어지는 대로 처리를 해라 라는 뜻
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [207]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [208]:
a.reshape(3, -1).shape

(3, 4)

In [209]:
a.reshape(2, 2, -1).shape

(2, 2, 3)

In [211]:
# 컴퓨터가 알아서 맞춰주려면 나누어 떨어지는 숫자로 쉐입을 맞추어 주어야 함.
# 안그러면 에러가 난다.

a.reshape(2, -1, 2).shape

(2, 3, 2)

In [215]:
# 다차원 배열을 1차원으로 펼치기 위해서는 flatten 혹은 ravel 메서드를 사용한다.

In [216]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [217]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [218]:
# 배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행,
# 열의 개수가 (5,1)인 2차원 배열 또는 행,
# 열의 개수가 (1,5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점입니다.

In [233]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [234]:
id(x)

140517106937264

In [235]:
# 얘랑

x.reshape(1,5)


array([[0, 1, 2, 3, 4]])

In [236]:
id(x)

140517106937264

In [237]:
# 얘는 엄연히 다른 객체라는 것.

x.reshape(5,1)


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [238]:
id(x)

140517106937264

In [239]:
# 같은 배열에 대해 차원만 1차원 증가시키는 경우
# newaxis 명령을 사용하기도 한다.

x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 행의 수나 열의 수가 같은 두개 이상의 배열을 연결(concatenate)하여 더 큰 배열을 만들 때 쓰는 명령어
# hstack
# vstack
# dstack
# stack
# r_
# c_
# tile
# hstack

In [240]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [241]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [242]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [246]:
# vstack은 열의 수가 같은 두개 이상의 배열을 위아래로 연결해 행의 수가 더 많은 배열을 만든다.
# 연결할 배열은 마찬가지로 하나의 리스트에 담는다.

b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [247]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dstack 명령은 깊이 방향으로 배열을 합친다.
# 가장 안쪽의 원소의 차원이 증가한다.
# 가장 내부의 숫자 원소가 배열이 된다.


In [249]:
# 이 예제의 경우 shape 변화가 2개의 (3x4) -> 1개의 (3x4x2)가 된다.

In [250]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [251]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [252]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [253]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [254]:
# stack은 dstack의 기능을 확장한 것으로
# dstack 처럼 마지막 차원으로 연결하는 것이 아니라
# 사용자가 지정한 차원(축으로) 배열을 연결합니다.
# axis 인수(디폴트0)를 사용하여 연결후의 회정 방향을 정한다.
# 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성된다.
# 즉 배열 두개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 한다.


In [262]:
c=np.stack([c1,c2])
c


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [263]:
c.shape


(2, 3, 4)

In [267]:
c=np.stack([c1,c2], axis=1)
c


array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [268]:
c=np.stack([c1,c2], axis=2)
c


array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [273]:
d1 = np.ones((4,5))
d2 = np.zeros((4, 5))
d3 = np.arange(20).reshape(4,5)

In [274]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [275]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [276]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [278]:
np.stack([d1, d2, d3])

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [279]:
np.stack([d1, d2, d3], axis=0)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [282]:
np.stack([d1, d2, d3], axis=1)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [283]:
np.stack([d1, d2, d3], axis=1).shape

(4, 3, 5)

In [284]:
np.stack([d1, d2, d3], axis=2)

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [285]:
np.stack([d1, d2, d3], axis=2).shape

(4, 5, 3)

In [287]:
# r_ 메서드는 소괄호()를 사용하지 않고 대괄호[]를 쓴다. 이런 특수 메서드를 인덱서라고 함.

np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [289]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [290]:
# tile 명령은 동일한 배열을 반복해 연결한다.

a = np.array([[0, 1, 2],[3, 4, 5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [291]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [292]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [294]:
np.tile(a, (4,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [332]:
x = np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [333]:
y = np.ones((3,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [334]:
xy = np.hstack([x, y])
xy

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [335]:
a11 = np.arange(10, 151, 10) # 0 .. n-1
a11

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [336]:

a12 = a11.reshape(3,5)
a12

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [337]:
xya11_stack = np.stack([xy, a12])
xya11_stack

array([[[  0.,   0.,   0.,   1.,   1.],
        [  0.,   0.,   0.,   1.,   1.],
        [  0.,   0.,   0.,   1.,   1.]],

       [[ 10.,  20.,  30.,  40.,  50.],
        [ 60.,  70.,  80.,  90., 100.],
        [110., 120., 130., 140., 150.]]])

In [338]:
xya11_stack2 = xya11_stack.reshape(6,5)
xya11_stack2

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [339]:
np.tile(xya11_stack2, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [340]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.arange(10, 151, 10)
c = c.reshape(3,5)
d = np.hstack((a, b))
e = np.vstack((d, c))
f = np.tile(e, (2,1))
f

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [348]:
x = np.zeros((3,3))
y = np.ones((3,2))
xy = np.hstack([x, y])
a11 = np.arange(10, 151, 10)
a12 = a11.reshape(3,5)
xya11_stack2 = xya11_stack.reshape(6,5)
np.tile(xya11_stack2, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [349]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [350]:
100 * x

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900])

In [352]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [354]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [356]:
# 보통 배열끼리 산술 연산을 하려면 두 배열의 shapes가 정확히 같아야 한다.

# 넘파이는 모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환시켜주는 브로드캐스팅을 지원한다.
# 넘파이의 브로드캐스팅방법은 더 작은 배열이 더 큰 배열에 호환되는 모양으로 확장되는 방식으로 진행된다.

a = np.array([1.0, 2.0, 3.0])
b = 2.0
a*b

array([2., 4., 6.])

In [357]:
#두 예제 중 무엇이 더 효율적인 코드일까?

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2., 2.0])
a*b

array([2., 4., 6.])

In [358]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a*b

array([2., 4., 6.])

In [360]:
import numpy as np
import random

test = np.array([random.randint(1,99) for i in range (20)]).reshape(2, 5, -1)

In [362]:
test

array([[[67, 46],
        [62, 15],
        [47, 78],
        [62, 55],
        [ 6, 84]],

       [[18, 88],
        [60, 39],
        [49, 56],
        [11, 65],
        [68, 14]]])

In [363]:
np.min(test, axis = 0)

array([[18, 46],
       [60, 15],
       [47, 56],
       [11, 55],
       [ 6, 14]])

In [364]:
np.min(test, axis = 2)

array([[46, 15, 47, 55,  6],
       [18, 39, 49, 11, 14]])

In [368]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [369]:
# all 은 모든 요소가 true이면 true를 반환한다.

((a <= b) & (b <= c)).all()

True

In [370]:
# any 는 하나라도 false면 false를 반환한다.

((a <= b) & (b <= c)).any()

True

In [ ]:
# 전체의 최대값 ㅇ
# 행 간의 합 ㅇ
# 행 간의 최대값 ㅇ
# 열 간의 평균 ㅇ
# 열 간의 최소값 ㅇ

In [373]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                                [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                                [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                                [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                                [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])
practice

array([[1.1, 7.1, 8. , 2.1, 6.5, 7.2],
       [2.7, 5.2, 3.3, 9. , 7.7, 2.8],
       [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
       [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
       [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [379]:
# axis=0 는 행 간의 연산 결과를 구한다. 
practice.sum(axis=0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [388]:
# axis=1 는 열 간의 연산 결과를 구한다. 
a = practice.sum(axis=1) 
a / len(a)

array([6.4 , 6.14, 6.86, 4.94, 5.94])

In [381]:
# 열 간의 최소값
np.min(practice, axis =1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [383]:
# 행 간의 최대값
np.max(practice, axis =0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [386]:
practice.max()

9.0

In [389]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a


array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [392]:
# 1은 행을 정렬한다.
a.sort(axis=1)
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [393]:
# 0은 열을 정렬한다.

a.sort(axis=0)
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [398]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령어를 사용한다.
# 주소값으로 출력하는 명령어이다.
# 순서대로 나열 했을 때 위 리스트의 몇 번 인덱스가 오게 되는지를 보여줌.

a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [399]:
a[j]

array([12, 25, 38, 42])

In [405]:
scores = np.array([[1,2,3,4],
                  [46, 99, 100, 71],
                  [81, 59, 90, 100]])

h = np.argsort(scores[1,:])
h

array([0, 3, 1, 2])

In [406]:
print(scores[:,h])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [408]:
s = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
s = s[:, s[1, :].argsort()]
s

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [464]:
np.random.seed(0)

In [465]:
a= np.random.randint(2, size=100)
a

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [466]:
np.mean(a)

0.56

In [467]:
asum = a.sum(axis=0)
asum /100

0.56

In [468]:
np.random.seed(0)
a= np.random.randint(2, size=100)
np.mean(a)

0.56

In [3]:
import numpy as np

In [5]:
np.random.seed(0)
a= np.random.randint(1, 7, size =100)
a

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2, 6, 1,
       2, 5, 4, 1, 4, 6, 1, 3, 4, 1, 2, 4, 6, 4, 4, 1, 2, 2, 2, 1, 3, 5,
       4, 4, 3, 5, 3, 1, 1, 5, 6, 6, 1, 5, 2, 5, 2, 3, 3, 1, 2, 2, 2, 2,
       4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5, 5, 5, 4, 5, 5, 5, 1, 5, 4,
       3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1])

In [6]:
np.mean(a)

3.42

In [341]:
# a[x,y]

a[1,2]

0.0

In [95]:
# a[0~1][0~3]
a.shape

(2, 4)

In [96]:
a[1][3]

7

In [97]:
test = [[0,1,2,3],[4,5,6,7]] #list
test

[[0, 1, 2, 3], [4, 5, 6, 7]]

In [98]:
test[1][2]

6

In [7]:
a = np.array([[1,2,3],
              [4,5,6],])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b = np.array([[7,8,9],
              [10,11,12]])
b


array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [16]:
c = np.arange(1,10) 
c*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [28]:
d = np.zeros(10)
d
d[4] = 1
d

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [34]:
e = np.arange(50)
e[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [64]:
# 빈 스트링 생성

f = np.zeros((3,3), dtype = "U10")
f

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U10')

In [65]:
f = np.stack([f,f,f], axis=0)
f

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [67]:
# 하나의 특정 값으로 배열의 값을 채우고 싶을 때는 np.full() 메서드를 활용하면 좋다.
# 첫번째 인자는 쉐입, 두번째 인자에는 요소로 채울 값을 전달하면 된다.
# 타입을 명시하길 원하면 dtype 키워드 인수를 사용하면 된다.

np.full((3,3,3), '', dtype="U10")

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [93]:
array4 = np.array([[['','','']]*3]*3, dtype='U10')
array4

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [95]:
a = np.zeros((3,3,3) , dtype = '<U10') # 3x3x3 배열을 갖고, 최대 10글자 출력
a

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [96]:
np.full((3,3,3), 'Playdata', dtype="U8")

array([[['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata']],

       [['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata']],

       [['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata']]], dtype='<U8')

In [97]:
g = np.arange(40,0,-2) 
g = g[::-1]
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [99]:
g = np.arange(2,41,2) 
g.reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [98]:
g.reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [100]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
h = np.ones((2,3,2))
h

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [111]:
h.astype("i")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [118]:
np.random.seed(0)
i= np.random.randint(2, size=9)
i

array([0, 1, 1, 0, 1, 1, 1, 1, 1])

In [119]:
i=i.astype(bool)
i.reshape(3,3)


array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [146]:
np.random.seed(0)
j= np.random.rand(10)
j

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [147]:
j=j*10

In [148]:
j=j.astype(int)
j

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [265]:
k = np.ones((10,10))
k

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [266]:
k[1:9, 1:9] = 0
k

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
c=np.stack([c1,c2], axis=1)

In [193]:
a = [0, 1, 2, 3, 4, 5, 6, 7]

a[0: 4: 3]

[0, 3]

In [261]:
k = np.ones((10,10))
k[1:-1, 1:-1] = 0
k

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [262]:
k = np.ones((10,10))
k[1:9, 1:9] = 0
k

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [263]:
k = np.zeros((10,10))
k[1:-1, 1:-1] = 1
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [264]:
k = np.zeros((10,10))
k[1:-1] = 1
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [462]:
k = np.ones((10,10))
k[:, [0,-1]] = 0
k[[0,-1], :] = 0
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [580]:
m = np.ones((8,8))
m[1::2, 1::2]=0
m[::2, ::2]=0
m

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [582]:
a13 = np.ones((8,8))
a13[::2, 1::2] = 0
a13[1::2, ::2] = 0
a13

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [587]:
n = np.array([[1,0],[0,1]])
n

array([[1, 0],
       [0, 1]])

In [589]:
np.tile(n, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [590]:
np.tile(np.eye(2), (4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [591]:
l = np.arange(1,5)
print(l)

even = np.array([True if i%2==0 else False for i in range (1,5)])
print(even)

[1 2 3 4]
[False  True False  True]


In [648]:
o = np.arange(11)
o[(3<o) & (7>o)] *= -1
o

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [666]:
p = np.arange(0, 101, 3)
p.sum(axis=0)

1683

In [611]:
 In[2]

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
c = np.arange(1, 10).reshape(3, 3)

# 조건문
condition = c % 2 == 0

# 조건을 만족하는 요소는 0로 바꾼다.
c[condition] = 0

# 조건을 만족하지 않는 요소는 1로 치환한다.
c[~condition] = 1

print(c)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [667]:
a = np.arange(1, 10).reshape(3, 3)

# 짝수는 0, 홀수는 1으로 치환한다.
b = np.where(a % 2 == 0, 0, 1)

print(b)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [679]:
q = np.linspace(0.1, 0.9, 9)
q

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [675]:
# 배열 생성
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
# 5개 숫자를 같은 차이, 범위값으로 생성한다.

ex = np.linspace(0, 100, 5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [762]:
while True:
    n = input("자연수를 입력해주세요.")
    try:
        for i in range(int(n)):
            k = np.array([np.random.choice(np.arange(1, 46), replace=False) for _ in range(6)])
            print(np.sort(k))
        break;
    except ValueError:
        print("자연수를 입력해주세요.")

자연수를 입력해주세요. 5


[ 1  4  6 10 17 26]
[ 7 17 19 36 41 41]
[10 15 24 27 43 44]
[ 8 12 33 42 43 44]
[ 9  9 11 41 42 42]


In [766]:
while True:
    try:
        count = int(input("로또 몇개 드릴까요?"))
        if count <= 0:
            raise Error
        numbers = np.arange(1,46)
        lottos = [np.sort(np.random.choice(numbers, 6, replace=False)) for i in range (count)]
        display(lottos)
        break
    except:
        print("자연수만 입력해주세요.")

로또 몇개 드릴까요? 7


[array([ 2, 16, 17, 32, 38, 42]),
 array([ 4,  9, 12, 13, 22, 32]),
 array([ 4,  6, 30, 34, 39, 40]),
 array([ 1,  4,  9, 36, 40, 45]),
 array([ 1, 21, 25, 31, 39, 41]),
 array([10, 13, 24, 30, 39, 43]),
 array([ 2, 19, 21, 23, 25, 26])]

In [ ]:
easy_list = [[1,2,3,4,5], [3,4]]

while i < len(easy_list):
    j = 0
    while j < len(easy_list[i]):
        print(easy_list[i][j])
        j += 1
    i += 1

In [783]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])

len(resp_time[resp_time>200])

8

In [784]:
(resp_time > 200).sum()

8

In [785]:
np.percentile(resp_time, 25) # 1사분위 수

71.5

In [786]:
np.percentile(resp_time, 50) # 2사분위 수

131.0

In [787]:
np.percentile(resp_time, 75) # 3사분위 수

175.5

In [788]:
np.percentile(resp_time, 100) # 최대값

218.0

In [799]:
for i, v in enumerate(range(25, 76, 25)):
    print(f'{i+1}분위 {v}% 값: {np.percentile(resp_time, v)}ms')

1분위 25% 값: 71.5ms
2분위 50% 값: 131.0ms
3분위 75% 값: 175.5ms


In [789]:
p = ["뽀로로", "루피", "크롱"]

result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
0, 1])
result

array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
       1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
       2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
       2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
       2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
       1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
       2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
       0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
       0, 1])

In [805]:
x = len(result[result==2])
print(x)
y = len(result[result==1])
print(y)
z = len(result[result==0])
print(z)

66
53
81


In [826]:
a = np.bincount(result, minlength=3)
b = a.argmax()
print(f"{p[b]}가 {a[b]}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [815]:
a

array([81, 53, 66])

In [816]:
b

0

0

In [808]:
index, count = np.unique(a, return_counts = True)
index

array([53, 66, 81])

In [823]:
m, n = np.unique(result, return_counts=True)
print(p[np.argmax(n)])

뽀로로


In [810]:
count

array([1, 1, 1])

In [801]:
import collections
p=["뽀로로","루피","크롱"]
x=np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
dic = dict(collections.Counter(x))
print(f'{p[max(dic,key=dic.get)]}가(이) {max(dic.values())}표로 반장으로 선출되었습니다.')

뽀로로가(이) 81표로 반장으로 선출되었습니다.
